FROM registry.cn-hangzhou.aliyuncs.com/prk/centos7_jdk1.8
MAINTAINER  pengrk "546711211@qq.com"

RUN yum -y update; yum clean all
RUN yum -y install epel-release; yum clean all
RUN yum -y install nodejs npm; yum clean all